@accessToken = paste_your_access_token_here


### Register user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "yossi@example.com",
  "password": "StrongPassword123"
}

### Login user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yossi@example.com",
  "password": "StrongPassword123"
}



### Get current authenticated user
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{accessToken}}


### Logout user
DELETE http://localhost:3000/api/auth/logout
Authorization: Bearer {{accessToken}}